fragment Bookmark on Bookmarks {
  id
  title
  image
  description
  createdAt
  collectionId
  url
  summary
}

fragment BookmarkDetails on Bookmarks {
  ...Bookmark
  createdBy {
    id
    name
    email
  }
  articleData
  embedData
  text
  html
  createdAt
  updatedAt
}
query GetBookmarksByCollection($collectionId: String!, $limit: Int = 1000) {
  bookmarks(
    where: { collectionId: { _eq: $collectionId } }
    orderBy: { createdAt: DESC }
    limit: $limit
  ) {
    ...Bookmark
  }
}
query GetBookmarksCountByCollection($collectionId: String!) {
  bookmarksAggregate(where: { collectionId: { _eq: $collectionId } }) {
    aggregate {
      count
    }
  }
}

query GetBookmarksByCollectionForSearchImport($collectionId: String!) {
  bookmarks(
    where: { collectionId: { _eq: $collectionId } }
    orderBy: { createdAt: DESC }
  ) {
    ...Bookmark
    createdBy {
      id
      name
      email
    }
    text
    createdAt
  }
}

query GetBookmarksByUser($userId: uuid!) {
  bookmarks(
    where: { createdById: { _eq: $userId } }
    orderBy: { createdAt: DESC }
  ) {
    ...Bookmark
    collection {
      name
      id
    }
  }
}

query GetBookmarkById($id: String!) {
  bookmark: bookmarksByPk(id: $id) {
    ...BookmarkDetails
    embeddings(orderBy: { chunkIndex: ASC }) {
      id
      chunkIndex
      chunk
    }
  }
}

query GetBookmarkByIdWithEmbedding($id: String!) {
  bookmark: bookmarksByPk(id: $id) {
    collectionId
    ...BookmarkDetails
    embeddings(orderBy: { chunkIndex: ASC }) {
      id
      chunkIndex
      chunk
      embedding
    }
  }
}
