mutation CreateCollection($name: String!, $userId: uuid!) {
  collection: insertCollectionsOne(
    object: {
      name: $name
      roles: {
        data: { userId: $userId, role: "owner" }
        onConflict: { constraint: collection_roles_pkey, updateColumns: [role] }
      }
    }
    onConflict: { constraint: collections_pkey, updateColumns: [name] }
  ) {
    id
    name
  }
}
